#!/bin/bash -
# Switch to the `~/.vim` directory
cd ~/.vim
# Pull
git pull
# Fetch submodules
# git submodule init
# git submodule update
# Upgrade all bundled plugins
# git submodule foreach git pull origin master
# Install/update bundles
vim +BundleInstall +qall
vim +BundleUpdate +qall
vim +BundleClean +qall
